spring:
  cloud:
    gateway:
      locator:
        enabled: true
      #路由功能
      routes:
      # 认证中心
      - id: spfd-auth
        #目标路径（分lb(注册中心名称)和ws(webservice路径)）
        uri: lb://spfd-auth
        #规则路径匹配
        predicates:
        - Path=/auth/**
        #拦截器组合
        filters:
        - SwaggerHeaderFilter
          # 验证码处理
        - ValidateCodeGatewayFilter
          # 前端密码解密
        - PasswordDecoderFilter
      #UPMS 模块
      - id: spfd-upms
        uri: lb://spfd-upms
        predicates:
        - Path=/admin/**
        filters:
          # 限流配置
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@remoteAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
          # 降级配置
        - name: Hystrix
          args:
            name: default
            fallbackUri: 'forward:/fallback'
      # 代码生成模块
      - id: spfd-codegen
        uri: lb://spfd-codegen
        predicates:
        - Path=/gen/**


security:
  encode:
    # 前端密码密钥，必须16位
    key: 'thanks,pig4cloud'

# 不校验验证码终端
ignore:
  clients:
    - test
  urls:
    - /static/**
