security:
  oauth2:
    client:
      client-id: ENC(imENTO7M8bLO38LFSIxnzw==)
      client-secret: ENC(i3cDFhs26sa2Ucrfz2hnQw==)
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: konsung_!@#$
    url: jdbc:mysql://pig-mysql:3306/ksbs?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  main:
    web-environment:true
  thymeleaf:
    mode:  HTML5
    encoding: UTF-8
    content-type: text/html
    cache: true
  mvc:
     static-path-pattern:/**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/view/console.html
# 直接放行URL
ignore:
  urls:
    - /permcache/**